######################################################
##                                                  ##
##                SuperiorSkyblock 2                ##
##                Developed by Ome_R                ##
##                                                  ##
######################################################

# Whether crop-growth should be enabled.
# When disabled, the plugin will not alter crop growth.
crop-growth: true

# Whether mob drops should be enabled.
# When disabled, the plugin will not alter mob drops.
mob-drops: true

# Whether island-effects should be enabled.
# When disabled, the plugin will not give any effects to any players.
island-effects: true

# Whether spawner-rates should be enabled.
# When disabled, the plugin will not alter spawner rates.
spawner-rates: true

# Whether block-limits should be enabled.
# When disabled, the plugin will not limit placement of blocks.
block-limits: true

# Whether entity-limits should be enabled.
# When disabled, the plugin will not limit spawning of entities.
entity-limits: true

# All the upgrades of the plugin
# https://wiki.bg-software.com/superiorskyblock/upgrades
upgrades:
  hoppers-limit:
    '1':
      price: 1000.0
      price-type: "Money"
      block-limits:
        HOPPER: 16
      commands:
        - 'island admin setupgrade %player% hoppers-limit 2'
        - 'island admin msgall %player% &b&lStratoblock &c&l» &7&oYour hopper limit was increased to &a&o32&8&o!'
    '2':
      price: 10000.0
      price-type: "Money"
      block-limits:
        HOPPER: 32
      commands:
        - 'island admin setupgrade %player% hoppers-limit 3'
        - 'island admin msgall %player% &b&lStratoblock &c&l» &7&oYour hopper limit was increased to &a&o64&8&o!'
    '3':
      price: 25000.0
      price-type: "Money"
      block-limits:
        HOPPER: 64
      commands:
        - 'island admin setupgrade %player% hoppers-limit 4'
        - 'island admin msgall %player% &b&lStratoblock &c&l» &7&oYour hopper limit was increased to &a&o128&8&o!'
    '4':
      price: 100000.0
      price-type: "Money"
      block-limits:
        HOPPER: 128
      commands:
        - 'island admin setupgrade %player% hoppers-limit 5'
        - 'island admin msgall %player% &b&lStratoblock &c&l» &7&oYour hopper limit was increased to &a&o256&8&o!'
    '5':
      price: 0.0
      price-type: "Money"
      block-limits:
        HOPPER: 256
      commands:
        - 'island admin msg %player% &b&lStratoblock &c&l» &7&oYou have already reached the maximum upgrade for this&8&o!'
  crop-growth:
    '1':
      price: 10000.0
      price-type: "Money"
      crop-growth: 1
      commands:
        - 'island admin setupgrade %player% crop-growth 2'
        - 'island admin msgall %player% &b&lStratoblock &c&l» &7&oYour crop growth multiplier was increased to &f&ox&a&o2&8&o!'
    '2':
      price: 25000.0
      price-type: "Money"
      crop-growth: 2
      commands:
        - 'island admin setupgrade %player% crop-growth 3'
        - 'island admin msgall %player% &b&lStratoblock &c&l» &7&oYour crop growth multiplier was increased to &f&ox&a&o5&8&o!'
    '3':
      price: 100000.0
      price-type: "Money"
      crop-growth: 5
      commands:
        - 'island admin setupgrade %player% crop-growth 4'
        - 'island admin msgall %player% &b&lStratoblock &c&l» &7&oYour crop growth multiplier was increased to &f&ox&a&o10&8&o!'
    '4':
      price: 0.0
      price-type: "Money"
      crop-growth: 10
      commands:
        - 'island admin msg %player% &b&lStratoblock &c&l» &7&oYou have already reached the maximum upgrade for this&8&o!'
  spawner-rates:
    '1':
      price: 10000.0
      price-type: "Money"
      spawner-rates: 1
      commands:
        - 'island admin setupgrade %player% spawner-rates 2'
        - 'island admin msgall %player% &b&lStratoblock &c&l» &7&oYour spawner rates multiplier was increased to &f&ox&a&o2&8&o!'
    '2':
      price: 25000.0
      price-type: "Money"
      spawner-rates: 2
      commands:
        - 'island admin setupgrade %player% spawner-rates 3'
        - 'island admin msgall %player% &b&lStratoblock &c&l» &7&oYour spawner rates multiplier was increased to &f&ox&a&o5&8&o!'
    '3':
      price: 100000.0
      price-type: "Money"
      spawner-rates: 5
      commands:
        - 'island admin setupgrade %player% spawner-rates 4'
        - 'island admin msgall %player% &b&lStratoblock &c&l» &7&oYour spawner rates multiplier was increased to &f&ox&a&o10&8&o!'
    '4':
      price: 0.0
      price-type: "Money"
      crop-growth: 10
      commands:
        - 'island admin msg %player% &b&lStratoblock &c&l» &7&oYou have already reached the maximum upgrade for this&8&o!'
  mob-drops:
    '1':
      price: 10000.0
      price-type: "Money"
      mob-drops: 1
      commands:
        - 'island admin setupgrade %player% mob-drops 2'
        - 'island admin msgall %player% &b&lStratoblock &c&l» &7&oYour mob drops multiplier was increased to &f&ox&a&o2&8&o!'
    '2':
      price: 25000.0
      price-type: "Money"
      mob-drops: 2
      commands:
        - 'island admin setupgrade %player% mob-drops 3'
        - 'island admin msgall %player% &b&lStratoblock &c&l» &7&oYour mob drops multiplier was increased to &f&ox&a&o5&8&o!'
    '3':
      price: 100000.0
      price-type: "Money"
      mob-drops: 5
      commands:
        - 'island admin setupgrade %player% mob-drops 4'
        - 'island admin msgall %player% &b&lStratoblock &c&l» &7&oYour mob drops multiplier was increased to &f&ox&a&o10&8&o!'
    '4':
      price: 0.0
      price-type: "Money"
      mob-drops: 10
      commands:
        - 'island admin msg %player% &b&lStratoblock &c&l» &7&oYou have already reached the maximum upgrade for this&8&o!'
  members-limit:
    '1':
      price: 1000.0
      price-type: "Money"
      team-limit: 6
      commands:
        - 'island admin setupgrade %player% members-limit 2'
        - 'island admin msgall %player% &b&lStratoblock &c&l» &7&oYour members limit was increased to &a&o8&8&o!'
    '2':
      price: 1000.0
      price-type: "Money"
      team-limit: 8
      commands:
        - 'island admin setupgrade %player% members-limit 3'
        - 'island admin msgall %player% &b&lStratoblock &c&l» &7&oYour members limit was increased to &a&o10&8&o!'
    '3':
      price: 5000.0
      price-type: "Money"
      team-limit: 10
      commands:
        - 'island admin setupgrade %player% members-limit 4'
        - 'island admin msgall %player% &b&lStratoblock &c&l» &7&oYour members limit was increased to &a&o12&8&o!'
    '4':
      price: 5000.0
      price-type: "Money"
      team-limit: 12
      commands:
        - 'island admin setupgrade %player% members-limit 5'
        - 'island admin msgall %player% &b&lStratoblock &c&l» &7&oYour members limit was increased to &a&o12&8&o!'
    '5':
      price: 5000.0
      price-type: "Money"
      team-limit: 14
      commands:
        - 'island admin setupgrade %player% members-limit 6'
        - 'island admin msgall %player% &b&lStratoblock &c&l» &7&oYour members limit was increased to &a&o14&8&o!'
    '6':
      price: 100000.0
      price-type: "Money"
      team-limit: 16
      commands:
        - 'island admin setupgrade %player% members-limit 7'
        - 'island admin msgall %player% &b&lStratoblock &c&l» &7&oYour members limit was increased to &a&o16&8&o!'
    '7':
      price: 0.0
      price-type: "Money"
      team-limit: 32
      commands:
        - 'island admin msg %player% &b&lStratoblock &c&l» &7&oYou have already reached the maximum upgrade for this&8&o!'
  border-size:
    '1':
      price: 30000.0
      price-type: "Money"
      border-size: 30
      commands:
        - 'island admin setupgrade %player% border-size 2'
        - 'island admin msgall %player% &b&lStratoblock &c&l» &7&oYour border size was increased to &a&o100x100&8&o!'
    '2':
      price: 80000.0
      price-type: "Money"
      border-size: 50
      commands:
        - 'island admin setupgrade %player% border-size 3'
        - 'island admin msgall %player% &b&lStratoblock &c&l» &7&oYour border size was increased to &a&o150x150&8&o!'
    '3':
      price: 150000.0
      price-type: "Money"
      border-size: 75
      commands:
        - 'island admin setupgrade %player% border-size 4'
        - 'island admin msgall %player% &b&lStratoblock &c&l» &7&oYour border size was increased to &a&o200x200&8&o!'
    '4':
      price: 200000.0
      price-type: "Money"
      border-size: 100
      commands:
        - 'island admin setupgrade %player% border-size 5'
        - 'island admin msgall %player% &b&lStratoblock &c&l» &7&oYour border size was increased to &a&o300x300&8&o!'
    '5':
      price: 500000.0
      price-type: "Money"
      border-size: 150
      commands:
        - 'island admin setupgrade %player% border-size 6'
        - 'island admin msgall %player% &b&lStratoblock &c&l» &7&oYour border size was increased to &a&o400x400&8&o!'
    '6':
      price: 0.0
      price-type: "Money"
      border-size: 200
      commands:
        - 'island admin msg %player% &b&lStratoblock &c&l» &7&oYou have already reached the maximum upgrade for this&8&o!'
  generator-rates:
    '1':
      price: 5000.0
      price-type: "Money"
      generator-rates:
        normal:
          STONE: 75
          COAL_ORE: 10
          IRON_ORE: 10
          COPPER_ORE: 5
      commands:
        - 'island admin setupgrade %player% generator-rates 2'
        - 'island admin msgall %player% &b&lStratoblock &c&l» &7&oYour generator was upgraded to &d&l&oTier &a&o28&o!'
    '2':
      price: 5000.0
      price-type: "Money"
      generator-rates:
        normal:
          STONE: 63
          COAL_ORE: 10
          IRON_ORE: 10
          COPPER_ORE: 5
          GOLD_ORE: 10
          LAPIS_ORE: 1
          REDSTONE_ORE: 1
      commands:
        - 'island admin setupgrade %player% generator-rates 3'
        - 'island admin msgall %player% &b&lStratoblock &c&l» &7&oYour generator was upgraded to &d&l&oTier &a&o38&o!'
    '3':
      price: 7000.0
      price-type: "Money"
      generator-rates:
        normal:
          STONE: 26
          COAL_ORE: 20
          IRON_ORE: 20
          COPPER_ORE: 10
          GOLD_ORE: 20
          LAPIS_ORE: 2
          REDSTONE_ORE: 2
      commands:
        - 'island admin setupgrade %player% generator-rates 4'
        - 'island admin msgall %player% &b&lStratoblock &c&l» &7&oYour generator was upgraded to &d&l&oTier &a&o48&o!'
    '4':
      price: 10000.0
      price-type: "Money"
      generator-rates:
        normal:
          STONE: 21
          COAL_ORE: 20
          IRON_ORE: 20
          COPPER_ORE: 10
          GOLD_ORE: 20
          DIAMOND_ORE: 5
          LAPIS_ORE: 2
          REDSTONE_ORE: 2
      commands:
        - 'island admin setupgrade %player% generator-rates 5'
        - 'island admin msgall %player% &b&lStratoblock &c&l» &7&oYour generator was upgraded to &d&l&oTier &a&o58&o!'
    '5':
      price: 0.0
      price-type: "Money"
      generator-rates:
        normal:
          STONE: 21
          COAL_ORE: 20
          IRON_ORE: 20
          COPPER_ORE: 10
          GOLD_ORE: 20
          DIAMOND_ORE: 5
          LAPIS_ORE: 2
          REDSTONE_ORE: 2
      commands:
        - 'island admin msg %player% &b&lStratoblock &c&l» &7&oYou have already reached the maximum upgrade for this&8&o!'
  entity-limits:
    '1':
      price: 10000.0
      price-type: "Money"
      entity-limits:
        SKELETON: 5
        ZOMBIE: 5
        CREEPER: 5
        SPIDER: 5
        CAVE_SPIDER: 5
        ENDERMAN: 5
        BLAZE: 5
        GHAST: 2
        SLIME: 5
        MAGMA_CUBE: 5
        WITHER_SKELETON: 2
        WITHER: 1
        WITCH: 2
      commands:
        - 'island admin setupgrade %player% entity-limits 2'
        - 'island admin msgall %player% &b&lStratoblock &c&l» &7&oYour entity limits was upgraded to &d&l&oTier &a&o28&o!'
    '2':
      price: 20000.0
      price-type: "Money"
      entity-limits:
        SKELETON: 10
        ZOMBIE: 10
        CREEPER: 10
        SPIDER: 10
        CAVE_SPIDER: 10
        ENDERMAN: 15
        BLAZE: 10
        GHAST: 5
        SLIME: 20
        MAGMA_CUBE: 10
        WITHER_SKELETON: 5
        WITHER: 1
        WITCH: 5
      commands:
        - 'island admin setupgrade %player% entity-limits 3'
        - 'island admin msgall %player% &b&lStratoblock &c&l» &7&oYour entity limits was upgraded to &d&l&oTier &a&o38&o!'
    '3':
      price: 50000.0
      price-type: "Money"
      entity-limits:
        SKELETON: 30
        ZOMBIE: 30
        CREEPER: 30
        SPIDER: 30
        CAVE_SPIDER: 30
        ENDERMAN: 50
        BLAZE: 30
        GHAST: 10
        SLIME: 50
        MAGMA_CUBE: 30
        WITHER_SKELETON: 10
        WITHER: 1
        WITCH: 10
      commands:
        - 'island admin setupgrade %player% entity-limits 4'
        - 'island admin msgall %player% &b&lStratoblock &c&l» &7&oYour entity limits was upgraded to &d&l&oTier &a&o48&o!'
    '4':
      price: 0.0
      price-type: "Money"
      entity-limits:
        SKELETON: 50
        ZOMBIE: 50
        CREEPER: 50
        SPIDER: 50
        CAVE_SPIDER: 50
        ENDERMAN: 75
        BLAZE: 50
        GHAST: 15
        SLIME: 75
        MAGMA_CUBE: 50
        WITHER_SKELETON: 30
        WITHER: 1
        WITCH: 30
      commands:
        - 'island admin msg %player% &b&lStratoblock &c&l» &7&oYou have already reached the maximum upgrade for this&8&o!'